sudo: required
services: 
    - docker

before_install:
    - docker build -t baris48/dokcer-react -f Dockerfile.dev .

script:
    - docker run -e CI=true baris48/dokcer-react npm run test

language: generic