sudo: required
services: 
    - docker

before_install:
    - docker build -t baris48/dokcer-react -f Dockerfile.dev .

script:
    - docker run -e CI=true baris48/dokcer-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-us-east-1-771619524940"
    bucket_path: "docker"
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:   
       secure: "$AWS_SECRET_KEY"

    
language: generic